<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: sans-serif; color: #334155; }
        .header { border-bottom: 2px solid #10b981; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { font-size: 24px; font-weight: bold; color: #0f172a; }
        .title { font-size: 18px; text-transform: uppercase; letter-spacing: 2px; color: #64748b; }
        .metric-grid { width: 100%; margin-bottom: 40px; }
        .metric-box { border: 1px solid #e2e8f0; padding: 15px; border-radius: 10px; }
        .label { font-size: 10px; text-transform: uppercase; color: #94a3b8; font-weight: bold; }
        .value { font-size: 20px; font-weight: bold; margin-top: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #f8fafc; text-align: left; padding: 10px; font-size: 10px; text-transform: uppercase; border-bottom: 1px solid #e2e8f0; }
        td { padding: 10px; font-size: 12px; border-bottom: 1px solid #f1f5f9; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #cbd5e1; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">SAHELPAY</div>
        <div class="title">Regional Health Brief: {{ $region }}</div>
        <p style="font-size: 12px;">Generated by {{ $manager_name }} on {{ $report_date }}</p>
    </div>

    <table class="metric-grid">
        <tr>
            <td class="metric-box">
                <div class="label">Total Network Liquidity</div>
                <div class="value">{{ number_format($total_liquidity, 2) }}</div>
            </td>
            <td class="metric-box">
                <div class="label">Revenue (MTD)</div>
                <div class="value">{{ number_format($monthly_revenue, 2) }}</div>
            </td>
            <td class="metric-box">
                <div class="label">Online Terminals</div>
                <div class="value">{{ $active_agents }}</div>
            </td>
        </tr>
    </table>

    <h3 class="title" style="font-size: 14px;">Top Performing Terminals</h3>
    <table>
        <thead>
            <tr>
                <th>Agent ID</th>
                <th>Operator Name</th>
                <th>Lifetime Volume</th>
            </tr>
        </thead>
        <tbody>
            @foreach($top_agents as $agent)
            <tr>
                <td>SP-{{ str_pad($agent->id, 5, '0', STR_PAD_LEFT) }}</td>
                <td>{{ $agent->name }}</td>
                <td>{{ number_format($agent->volume, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Confidential Internal Document - SahelPay Systems © 2026
    </div>
</body>
</html>